{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmio/rmio_{{ version }}.tar.gz
  sha256: 1ed6046ee36f34fca5357e0f18ab2f53b9d85032ec2cbcadb9f33a8fa7456dbe

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bigassertr
    - r-ff
  run:
    - r-base
    - r-bigassertr
    - r-ff

test:
  commands:
    - $R -e "library('rmio')"           # [not win]
    - "\"%R%\" -e \"library('rmio')\""  # [win]

about:
  home: https://github.com/privefl/rmio
  license: GPL-3.0-only
  summary: Provides header files of 'mio', a cross-platform C++11 header-only library for memory mapped file IO <https://github.com/mandreyel/mio>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rmio
# Title: Provides 'mio' C++11 Header Files
# Version: 0.2.0
# Authors@R: person(given = "Florian", family = "Prive", role = c("aut", "cre"), email = "florian.prive.21@gmail.com")
# Description: Provides header files of 'mio', a cross-platform C++11 header-only library for memory mapped file IO <https://github.com/mandreyel/mio>.
# License: GPL-3
# Copyright: file COPYRIGHTS
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# URL: https://github.com/privefl/rmio
# BugReports: https://github.com/privefl/rmio/issues
# NeedsCompilation: no
# Packaged: 2020-07-22 08:33:11 UTC; au639593
# Author: Florian Prive [aut, cre]
# Maintainer: Florian Prive <florian.prive.21@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-07-22 09:00:02 UTC
